#!/usr/bin/env bash
#Displays "Best School" 10 times using while loop
#On the 9th iteral displays "Hi" before "Best School"

cnt=0
while [ $cnt -lt 10 ]
do
	if [ $cnt -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( cnt++ ))
done
