#!/usr/bin/env bash
#Print numbers from 1 to 20
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
#use the while loop, use the case statement

cnt=1

while [ $cnt -le 20 ]
do
	echo "$cnt"
	case $cnt in
		"4") echo "bad luck from china";;
		"9") echo "bad luck from Japan";;
		"17" echo "bad luck from Italy";;
	esac
	(( cnt++ ))
done
